[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"


[project]
name = "eigenbridge"
authors = [
    { name = "Jonathan Waldrop", email = "jwaldrop@ameslab.gov" },
    { name = "Mahir Anand", email = "mahiranand@outlook.com" },
]
description = "Quantum eigensolver implementation using Qiskit"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dynamic = ["version"]
dependencies = [
    "numpy",
    "pybind11",
    "qiskit",
    "qiskit-algorithms",
    "qiskit-aer",
    "qiskit-ibm-runtime",
]

[project.optional-dependencies]
dev = ["pre-commit", "pytest"]

[tool.setuptools.packages.find]
where = ["python"]

[tool.setuptools_scm]
fallback_version = "0.0.0"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q -p no:warnings" # Silencing warnings b/c Qiskit
testpaths = [
    "tests",
]
