name: Merge Workflow

on:
  push:
    branches:
      - main

jobs:
  tag-commit:
    uses: NWChemEx/.github/.github/workflows/tag.yaml@master
    secrets: inherit

  deploy_to_pypi:
    needs: tag-commit
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Build PyPI Distribution
        uses: NWChemEx/.github/.github/actions/build_pypi_dist@master

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
