name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  # Build and test C++ libraries.
  test_cpp:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Install LAPACK and LAPACKE
        run: sudo apt-get install -y liblapacke-dev
        shell: bash
      - name: Install Python deps for embed and VQE
        run: |
          pip install pybind11 qiskit qiskit-algorithms numpy scipy
        shell: bash
      - name: Build and Test
        run: |
          toolchain=${PWD}/.github/workflow_toolchains/ubuntu-24.04.cmake
          cmake -Bbuild -H. -GNinja \
            -DCMAKE_TOOLCHAIN_FILE="${toolchain}" \
            -Dpybind11_DIR="$(python -m pybind11 --cmakedir)"
          cmake --build build --parallel
          cd build
          ctest -C Debug -T test -VV --no-tests=error
        shell: bash

  # Build and test Python bindings.
  test_python:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install LAPACK and LAPACKE
        run: sudo apt-get install -y liblapacke-dev
        shell: bash
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Build and Test
        run: |
          pip install .
          cd tests/unit_tests
          python -m unittest
        shell: bash

  # Run pre-commit hooks
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Install and Run pre-commit
        run: |
          pip install -r requirements.txt
          pre-commit run --all-files
        shell: bash
