name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  # Build and test Python bindings.
  test_python:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install LAPACK and LAPACKE
        run: sudo apt-get install -y liblapacke-dev
        shell: bash
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Build and Test
        run: |
          pip install .
          cd tests/unit_tests
          python -m unittest
        shell: bash

  test_pypi_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build PyPI Distribution
        uses: NWChemEx/.github/.github/actions/build_pypi_dist@master

  # Run pre-commit hooks
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Install and Run pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files
        shell: bash
